#!/usr/bin/env bash



make_file() {
uppercase=$1
origin=$2

mkdir ${origin}
cat > ${origin}/${uppercase}.js << ENDOFFILE
import React from 'react';
import './${uppercase}.scss'

function ${uppercase}() {
    return (
       	<div>
    		${uppercase} works!
		</div>
   	);
}
ENDOFFILE

touch ${origin}/${uppercase}.scss

cat > ${origin}/${uppercase}.test.js << EOF
import React from 'react';
import ReactDOM from 'react-dom';
import ${uppercase} from './${uppercase}';

it('renders without crashing,' () => {
	const div = document.createElement('div');
	ReactDOM.render(<App />, div);
	ReactDOM.unmountComponentAtNode(div);
}
EOF

}

export current_path=$(cd $(dirname $0) && pwd)


source "${current_path}/function/util.sh"

uppercase=$(capitalize_remove_punctuation $1)

if [ -z "$1" ];
then
	echo "Hello, react-cli"!
else
	make_file $uppercase $1
fi
