#!/usr/bin/env bash



current_path=$(cd $(dirname $0) && pwd)


source "${current_path}/function/util.sh"


strindex 'hello' 'e'

echo $BASH_VERSION

uppercase=${1^}

cat > $1.js << ENDOFFILE

import React from 'react';
import './${uppercase}.scss'

function ${uppercase} {
    return (
        <div>
	    	${uppercase} works!
		</div>
    );
}
ENDOFFILE

